/**
 * Section 5: Footer
 * Page footer with branding and generation metadata.
 *
 * Props:
 *   - brand: string (product name)
 *   - year: string (copyright year)
 */
// STRUCTURAL CONTRACT v2
// ┌──────────────────────────────────────────────────────────┐
// │  [Brand] © [Year]                [Generated by ...]      │
// └──────────────────────────────────────────────────────────┘
export default function Footer({ brand, year }) {
  return (
    <footer
      style={{
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        padding: "16px 32px",
        borderTop: "1px solid #E2E8F0",
        width: "1440px",
        height: "80px",
        boxSizing: "border-box",
      }}
    >
      <span style={{ fontFamily: "Inter", fontSize: "12px", color: "#64748B" }}>
        {brand} © {year}
      </span>
      <span style={{ fontFamily: "Inter", fontSize: "12px", color: "#94A3B8" }}>
        Generated by export-design skill
      </span>
    </footer>
  );
}
