import type { PricingCatalog } from "./pricing.js";

const pricingCatalog = {
  schema: "crucible.usage-ledger.pricing-catalog.v2",
  retrieval_date: "2026-06-18",
  freshness_window_days: 180,
  currency: "USD",
  weight_ratios: {
    anthropic: { input: 1, output: 5, cache_write: 1.25, cache_read: 0.1 },
    openai: { input: 1, output: 6, cache_write: 1.25, cache_read: 0.1 },
  },
  prices: [
    {
      provider: "anthropic",
      model_pattern: "^opus$",
      precedence: 10,
      billing_mode: "subscription_included",
      effective_date: "2026-06-18",
      retrieval_date: "2026-06-18",
      source: "Claude Code costs and Pro/Max plan docs",
      source_url: "https://code.claude.com/docs/en/costs",
      source_note:
        "The repo lane alias anthropic/opus is authenticated through Claude Code subscription OAuth. Claude Code says Pro/Max subscribers have included usage and local session dollar figures are not authoritative billing.",
      input_per_million_usd: null,
      output_per_million_usd: null,
      cache_read_per_million_usd: null,
      cache_write_per_million_usd: null,
      reasoning_output_per_million_usd: null,
    },
    {
      provider: "anthropic",
      model_pattern: "^sonnet$|^haiku$|^fable$",
      precedence: 10,
      billing_mode: "subscription_included",
      effective_date: "2026-06-18",
      retrieval_date: "2026-06-18",
      source: "Claude Code costs and Pro/Max plan docs",
      source_url: "https://code.claude.com/docs/en/costs",
      source_note:
        "Short repo aliases are Claude Code subscription lanes. Use provider-reported cost or allowance samples; do not estimate subscription dollar cost from tokens.",
      input_per_million_usd: null,
      output_per_million_usd: null,
      cache_read_per_million_usd: null,
      cache_write_per_million_usd: null,
      reasoning_output_per_million_usd: null,
    },
    {
      provider: "anthropic",
      model_pattern: "claude[-_]?opus[-_]?4[-_]?(8|7|6|5)?|claude.*opus",
      precedence: 50,
      billing_mode: "api_token",
      effective_date: "2026-06-18",
      retrieval_date: "2026-06-18",
      source: "Anthropic Claude API pricing",
      source_url: "https://platform.claude.com/docs/en/about-claude/pricing",
      source_note:
        "Standard Claude API Opus 4.5 and later rates. cache_write_per_million_usd uses the 5-minute cache write price; 1-hour cache writes require an explicit override.",
      input_per_million_usd: 5,
      output_per_million_usd: 25,
      cache_read_per_million_usd: 0.5,
      cache_write_per_million_usd: 6.25,
      reasoning_output_per_million_usd: null,
    },
    {
      provider: "anthropic",
      model_pattern: "claude[-_]?sonnet|claude.*sonnet",
      precedence: 50,
      billing_mode: "api_token",
      effective_date: "2026-06-18",
      retrieval_date: "2026-06-18",
      source: "Anthropic Claude API pricing",
      source_url: "https://platform.claude.com/docs/en/about-claude/pricing",
      source_note:
        "Standard Claude API Sonnet 4.5 and later rates. cache_write_per_million_usd uses the 5-minute cache write price.",
      input_per_million_usd: 3,
      output_per_million_usd: 15,
      cache_read_per_million_usd: 0.3,
      cache_write_per_million_usd: 3.75,
      reasoning_output_per_million_usd: null,
    },
    {
      provider: "anthropic",
      model_pattern: "claude[-_]?haiku|claude.*haiku",
      precedence: 50,
      billing_mode: "api_token",
      effective_date: "2026-06-18",
      retrieval_date: "2026-06-18",
      source: "Anthropic Claude API pricing",
      source_url: "https://platform.claude.com/docs/en/about-claude/pricing",
      source_note:
        "Standard Claude API Haiku 4.5 rates. cache_write_per_million_usd uses the 5-minute cache write price.",
      input_per_million_usd: 1,
      output_per_million_usd: 5,
      cache_read_per_million_usd: 0.1,
      cache_write_per_million_usd: 1.25,
      reasoning_output_per_million_usd: null,
    },
    {
      provider: "anthropic",
      model_pattern:
        "claude[-_]?fable|claude.*fable|claude[-_]?mythos|claude.*mythos",
      precedence: 50,
      billing_mode: "api_token",
      effective_date: "2026-06-18",
      retrieval_date: "2026-06-18",
      source: "Anthropic Claude API pricing",
      source_url: "https://platform.claude.com/docs/en/about-claude/pricing",
      source_note:
        "Standard Claude API Fable/Mythos rates. cache_write_per_million_usd uses the 5-minute cache write price.",
      input_per_million_usd: 10,
      output_per_million_usd: 50,
      cache_read_per_million_usd: 1,
      cache_write_per_million_usd: 12.5,
      reasoning_output_per_million_usd: null,
    },
    {
      provider: "openai",
      model_pattern: "^codex$",
      precedence: 10,
      billing_mode: "credit_allowance",
      effective_date: "2026-06-18",
      retrieval_date: "2026-06-18",
      source: "OpenAI Codex pricing",
      source_url: "https://developers.openai.com/codex/pricing",
      source_note:
        "Codex on ChatGPT plans consumes included limits or credits. The rate card is credits per million tokens, not USD; use provider-reported API cost or subscription allowance samples for this lane.",
      input_per_million_usd: null,
      output_per_million_usd: null,
      cache_read_per_million_usd: null,
      cache_write_per_million_usd: null,
      reasoning_output_per_million_usd: null,
    },
    {
      provider: "openai",
      model_pattern: "^gpt[-_]?5\\.5$|^gpt-5-5$",
      precedence: 50,
      billing_mode: "api_token",
      effective_date: "2026-06-18",
      retrieval_date: "2026-06-18",
      source: "OpenAI API pricing",
      source_url: "https://openai.com/api/pricing/",
      source_note:
        "Standard API pricing for GPT-5.5. cache_read_per_million_usd maps OpenAI cached input pricing.",
      input_per_million_usd: 5,
      output_per_million_usd: 30,
      cache_read_per_million_usd: 0.5,
      cache_write_per_million_usd: null,
      reasoning_output_per_million_usd: null,
    },
    {
      provider: "openai",
      model_pattern: "^gpt[-_]?5\\.4$|^gpt-5-4$",
      precedence: 50,
      billing_mode: "api_token",
      effective_date: "2026-06-18",
      retrieval_date: "2026-06-18",
      source: "OpenAI API pricing",
      source_url: "https://openai.com/api/pricing/",
      source_note:
        "Standard API pricing for GPT-5.4. cache_read_per_million_usd maps OpenAI cached input pricing.",
      input_per_million_usd: 2.5,
      output_per_million_usd: 15,
      cache_read_per_million_usd: 0.25,
      cache_write_per_million_usd: null,
      reasoning_output_per_million_usd: null,
    },
    {
      provider: "openai",
      model_pattern: "^gpt[-_]?5\\.4[-_]?mini$|^gpt-5-4-mini$",
      precedence: 50,
      billing_mode: "api_token",
      effective_date: "2026-06-18",
      retrieval_date: "2026-06-18",
      source: "OpenAI API pricing",
      source_url: "https://openai.com/api/pricing/",
      source_note:
        "Standard API pricing for GPT-5.4 mini. cache_read_per_million_usd maps OpenAI cached input pricing.",
      input_per_million_usd: 0.75,
      output_per_million_usd: 4.5,
      cache_read_per_million_usd: 0.075,
      cache_write_per_million_usd: null,
      reasoning_output_per_million_usd: null,
    },
    {
      provider: "deepseek",
      model_pattern: "^deepseek-v4-(pro|flash)$",
      precedence: 10,
      billing_mode: "diagnostic_only",
      effective_date: "2026-06-18",
      retrieval_date: "2026-06-18",
      source: "Crucible Pi lane usage artifact contract",
      source_url: "docs/usage-ledger-v2.md",
      source_note:
        "The Pi/DeepSeek lane currently emits progress diagnostics rather than true provider token/cost usage for these local aliases.",
      input_per_million_usd: null,
      output_per_million_usd: null,
      cache_read_per_million_usd: null,
      cache_write_per_million_usd: null,
      reasoning_output_per_million_usd: null,
    },
    {
      provider: "deepseek",
      model_pattern: "^deepseek-chat$",
      precedence: 50,
      billing_mode: "api_token",
      effective_date: "2026-06-18",
      retrieval_date: "2026-06-18",
      source: "DeepSeek API pricing",
      source_url:
        "https://api-docs.deepseek.com/quick_start/pricing-details-usd",
      source_note:
        "DeepSeek API pricing. input_per_million_usd uses cache-miss input; cache_read_per_million_usd uses cache-hit input.",
      input_per_million_usd: 0.27,
      output_per_million_usd: 1.1,
      cache_read_per_million_usd: 0.07,
      cache_write_per_million_usd: null,
      reasoning_output_per_million_usd: null,
    },
    {
      provider: "deepseek",
      model_pattern: "^deepseek-reasoner$",
      precedence: 50,
      billing_mode: "api_token",
      effective_date: "2026-06-18",
      retrieval_date: "2026-06-18",
      source: "DeepSeek API pricing",
      source_url:
        "https://api-docs.deepseek.com/quick_start/pricing-details-usd",
      source_note:
        "DeepSeek API pricing. input_per_million_usd uses cache-miss input; cache_read_per_million_usd uses cache-hit input.",
      input_per_million_usd: 0.55,
      output_per_million_usd: 2.19,
      cache_read_per_million_usd: 0.14,
      cache_write_per_million_usd: null,
      reasoning_output_per_million_usd: null,
    },
    {
      provider: "ds4-studio2",
      model_pattern: "^deepseek-v4-flash$",
      precedence: 10,
      billing_mode: "diagnostic_only",
      effective_date: "2026-06-18",
      retrieval_date: "2026-06-18",
      source: "Crucible Pi lane usage artifact contract",
      source_url: "docs/usage-ledger-v2.md",
      source_note:
        "The ds4-studio2 lane is a local Pi route and does not expose provider billable token/cost telemetry.",
      input_per_million_usd: null,
      output_per_million_usd: null,
      cache_read_per_million_usd: null,
      cache_write_per_million_usd: null,
      reasoning_output_per_million_usd: null,
    },
    {
      provider: "ornith-studio2",
      model_pattern: "^ornith-1\\.0-35b-q4_k_m$",
      precedence: 10,
      billing_mode: "diagnostic_only",
      effective_date: "2026-06-27",
      retrieval_date: "2026-06-27",
      source: "Crucible Pi lane usage artifact contract",
      source_url: "docs/usage-ledger-v2.md",
      source_note:
        "The Ornith studio2 lane is a local Pi route. Provider/runtime token telemetry may be recorded when Pi exposes it, but local llama.cpp usage has no provider-billed spend and remains diagnostic-only for cost.",
      input_per_million_usd: null,
      output_per_million_usd: null,
      cache_read_per_million_usd: null,
      cache_write_per_million_usd: null,
      reasoning_output_per_million_usd: null,
    },
  ],
} satisfies PricingCatalog;

export default pricingCatalog;
