/**
 * Section 10: Report Footer
 * Rebuilt from v5 footer.jsx inline styles.
 */

export interface ReportFooterProps {
  nextReport?: string;
}

export default function ReportFooter({ nextReport }: ReportFooterProps) {
  const nextLine = nextReport ?? "2026-03-25 06:00 ET";

  return (
    <div
      style={{
        backgroundColor: "#FFFFFF05",
        borderTopColor: "#FFFFFF0F",
        borderTopStyle: "solid" as const,
        borderTopWidth: "1px",
        boxSizing: "border-box" as const,
        display: "flex",
        flexDirection: "column" as const,
        fontSynthesis: "none",
        gap: "12px",
        MozOsxFontSmoothing: "grayscale",
        order: 10,
        paddingBlock: "32px",
        paddingInline: "64px",
        WebkitFontSmoothing: "antialiased",
        width: "1440px",
      }}
    >
      <div
        style={{
          boxSizing: "border-box" as const,
          color: "#FFFFFF40",
          fontFamily: '"JetBrains Mono", system-ui, sans-serif',
          fontSize: "11px",
          lineHeight: "14px",
        }}
      >
        Symphony Token Intelligence &middot; Generated by token-report.sh
        &middot; Data from ~/Library/Logs/symphony/
      </div>
      <div
        style={{
          boxSizing: "border-box" as const,
          color: "#FFFFFF33",
          fontFamily: '"DM Sans", system-ui, sans-serif',
          fontSize: "10px",
          lineHeight: "12px",
        }}
      >
        Retention: 90 days &middot; Next report: {nextLine} &middot; Inflection
        attribution uses &ldquo;coincides with&rdquo; language &mdash;
        hypotheses, not conclusions.
      </div>
    </div>
  );
}
