/**
 * Section 9: Report Footer
 * Converted from design reference ReportFooter.jsx.
 */
export default function ReportFooter() {
  return (
    <footer
      style={{
        color: "var(--text-muted)",
        fontSize: "0.8rem",
        marginTop: "40px",
        textAlign: "center",
      }}
    >
      Symphony Token Report &middot; Self-contained &middot; Generated by
      token-report.mjs &middot; SYMPH-131
    </footer>
  );
}
