{/*
  STRUCTURAL CONTRACT v1 — 2 direct children
  Labels: "Symphony Token Intelligence · Generated by token-report.sh · Data from ~/Library/Logs/symphony/", "Retention: 90 days · Next report: 2026-03-25 06:00 ET · Inflection attribution uses 'coincides with' language — hypotheses, not conclusions."
  PRESERVE: all children, all labels, all repeating groups
*/}
(
    <div style={{ borderTopColor: '#FFFFFF0F', borderTopStyle: 'solid', borderTopWidth: '1px', boxSizing: 'border-box', display: 'flex', flexDirection: 'column', fontSynthesis: 'none', gap: '8px', MozOsxFontSmoothing: 'grayscale', paddingBlock: '40px', paddingInline: '64px', WebkitFontSmoothing: 'antialiased', width: '1440px' }}>
      <div style={{ boxSizing: 'border-box', color: '#FFFFFF33', fontFamily: '"DM Sans", system-ui, sans-serif', fontSize: '12px', lineHeight: '16px' }}>
        Symphony Token Intelligence · Generated by token-report.sh · Data from ~/Library/Logs/symphony/
      </div>
      <div style={{ boxSizing: 'border-box', color: '#FFFFFF26', fontFamily: '"DM Sans", system-ui, sans-serif', fontSize: '12px', lineHeight: '16px' }}>
        Retention: 90 days · Next report: 2026-03-25 06:00 ET · Inflection attribution uses "coincides with" language — hypotheses, not conclusions.
      </div>
    </div>
  )